### ISSUE TITLE
Improve syntax consistency

### ISSUE THREAD

**Issue by mindplay-dk** [Rich-Harris/HTMLX#6]
The syntax of inline statements is rather inconsistent.

```
{#if porridge.temperature > 100}
  <p>too hot!</p>
{:elseif 80 > porridge.temperature}
  <p>too cold!</p>
{:else}
  <p>just right!</p>
{/if}
```

Why not simply reserve the words `if`, `elseif`, `else` and `endif` and avoid the mix of `#`, `:` and `/` symbols?

```
{if porridge.temperature > 100}
  <p>too hot!</p>
{elseif 80 > porridge.temperature}
  <p>too cold!</p>
{else}
  <p>just right!</p>
{endif}
```

In my opinion, this is less noisy, easier to read and faster to type.

**Comment by stalkerg** [comment]
I agree I ask about it in new syntax issue for Svelte too. It's bound with convenient for syntax analyzer.

**Comment by mindplay-dk** [comment]
I'm not a fan of Svelte's double-braces to qualify printable expressions - the only time it's ambiguous is if somebody wants to name variables like `if` and `else`, which they shouldn't be doing in the first place. I think it's completely okay to reserve these as keywords.

**Comment by arxpoetica** [comment]
One of the main reasons was to try and avoid reserving *any* words, but maybe if people feel that strongly...

An alternate approach that was floated (that I'm still a fan of) looked something like this:

```
if (expression) {
    <div>...</div>
} else if (expression2) {
    <div>...</div>
} else {
    <div>...</div>
}
```

I believe this was rejected for looking a little off, but I personally thought it read just fine. (If one used the Pug syntax though, the two might conflict). I could see why that one isn't popular but there's probably no reason it shouldn't still be in the running.

Beyond that, @Rich-Harris had a few other reasons; I'll let him (re)articulate

**Comment by Rich-Harris** [comment]
> The syntax of inline statements is rather inconsistent

'Inconsistent' is definitely the wrong word to use here! `#` opens a block, `/` closes it, and `:` opens a sub-clause, and that's true for all blocks everywhere. Anything between `{` and `}` *without* punctuation is consistently a JavaScript expression.

There are a few reasons to favour punctuation. Firstly, it's easier to grok the structure of a component when you're just scanning it — your brain doesn't need to stop and ask 'is this a special reserved word?'. The symmetry is clearer: when you see `#if`, you can scan down vertically until you see `{/`, rather than seeing a sea of lines beginning `{e`, which all resemble each other.

(That problem would be worse when you consider `each` — `endeach` is both clumsy and visually 'meh'.)

Secondly, reserving words like `elseif` and `each` is one of those things that seems like a small deal at the time, but turns out to have a significant cost. As a component author, you're never 100% confident that you're not accidentally going to use a reserved word in your expressions, unless you memorise the list (which tends to grow over time, once you've set the precedent that reserved words are okay) or keep referring to documentation. There is value in having a simple rule that between `{` and `}` you can put any JavaScript expression you like: it's simple, clear, and requires no framework- (or HTMLx-) specific knowledge.

Finally, as @stalkerg alluded to, it simplifies the job of tokenizing the language. That's not an overriding concern, but it does have value — for example, it makes it easier to build a language server that allows your editor to suggest `else` as an autocomplete option when you type `{:`, which in turn reduces the amount you end up typing.

> I'm not a fan of Svelte's double-braces to qualify printable expressions

They were [removed in v2](https://svelte.technology/blog/version-2) — HTMLx is basically the language Svelte currently uses.

**Comment by stalkerg** [comment]
> Secondly, reserving words like elseif and each is one of those things that seems like a small deal at the time, but turns out to have a significant cost.

I suppose it's a little wrong - we should talk about reserving {elseif and {each .
Also, about autocomlete - it will be same with '{e' and maybe better because to write ':' you should press shift+; but 'e' you can write without shift. 

I understand, syntax with {:,{#, {/ have some benefits but syntax without it look much clear. 

> . Firstly, it's easier to grok the structure of a component when you're just scanning it — your brain doesn't need to stop and ask 'is this a special reserved word?'.

If I remeber right about brain - for us much eaier to detect whole words insted rarely used in language symbols like :,#,\ . (For example in Russia we not use # at all, and on keyboard in this place we have №)

**Comment by Rich-Harris** [comment]
If you've just typed a `{` character then your finger is already on the shift key!

> If I remember right about the brain - for us much easier to detect whole words instead rarely used in language symbols like :,#,\ . (For example in the Russian language we not use # at all, and on the keyboard in this place we have №)

If that were true *in this context*, then we would write HTML like this:

```html
<header>
  <h1>Hello world!<endh1>
  <small>This would get annoying quickly<endsmall>
<endheader>

<main>
  <div>app goes here<enddiv>
<endmain>
```

**Comment by mindplay-dk** [comment]
> `#` opens a block, `/` closes it, and `:` opens a sub-clause, and that's true for all blocks everywhere

IMO, they're just noise - your brain can interpret words much faster without the added noise, and the words have to be there either way, so.

> Anything between `{` and `}` without punctuation is consistently a JavaScript expression.

IMO, not really helpful, because your brain will automatically learn to filter out the noisy punctuation anyway - you'll barely be able to see it, because your brain is so used to reading words, and that's how you'll parse the tags anyhow. You won't see the extra characters when you're skimming across the code, but you have the added burden of having to type them.

> That problem would be worse when you consider `each` — `endeach` is both clumsy and visually 'meh'

I could buy that one, sure - it's maybe easier to visually pair `each` with `/each` than `each` with `endeach`.

OTOH, `else` and `elseif` don't visually pair with `if` and `/if`, so it doesn't really solve that problem.

> Secondly, reserving words like elseif and each is one of those things that seems like a small deal at the time, but turns out to have a significant cost. As a component author, you're never 100% confident that you're not accidentally going to use a reserved word in your expressions, unless you memorise the list (which tends to grow over time...)

The Javascript keyword list `if`, `else`, `for`, `while`, etc. has not really grown over time though - it's been stable for 10+ years, and most likely this won't grow or change either.

It's only a small, finite set of reserved keywords - which everyone knows and has memorized from Javascript already anyhow, so there's no learning curve here in the first place.

Besides, I can't recall ever having wanted to use words like `for`, `while`, `if` or `else` as neither variable-names nor function-names or arguments or anything else.

> it makes it easier to build a language server that allows your editor to suggest `else` as an autocomplete option when you type `{:`

I don't think most people auto-complete keywords like `if` or `else` - neither Storm nor VS Code auto-completes keywords, as far as I'm aware. I wouldn't personally want my IDE to suggest keywords, the longest of which is probably `while`, which is just 5 characters. I don't think I've ever seen anybody who auto-completes keywords. You'd be the first I've known ;-)

I can respect the fact that this is all subjective and based on preference and experience - but personally, I feel this syntax is already much too punctuation-heavy, especially considering the small number of words/tokens in this fairly small language; the extra tokens don't help make this more readable, and definitely makes it much slower to type.

You have to memorize the keywords anyhow - but now, in addition to that, you have to memorize which symbol goes in front of every keyword. And these are largely keywords you already know from JS - from my point of view, having to learn the proper punctuation, in addition, only increases learning-curve.

Part of the selling point of having a standard for this, is IDE support - which means you'd have syntax-highlighting, which makes the extra punctuation even more redundant.

If punctuation is really necessary for parser and visual disambiguation, how about something more consistent with popular template languages like handlebars and dust, where punctuation is used only to indicate directives and end-of-block directives?

For example:

```
{#if porridge.temperature > 100}
  <p>too hot!</p>
{#elseif 80 > porridge.temperature}
  <p>too cold!</p>
{#else}
  <p>just right!</p>
{/if}
```

IMO, this is much easier to understand and memorize, more consistent with popular template languages - and a bit less noisy than the special punctuation for certain directives like `#else` and `#elseif`?

**Comment by mindplay-dk** [comment]
> It's very easy to know I'm somewhere in the middle and not the `{/end}`

Indentation, keywords *and* color-coding in your IDE isn't enough?

Well, I give up.

**Comment by arxpoetica** [comment]
> Indentation

If, else, and end if are on the same level, so that's no help.

> keywords

B'lieve it or not, there's a part of my brain preserved for lexical **reading** vs symbolic **scanning**. Those two parts operate very differently. Dunno. Maybe other people's brains work very differently.

>  and color-coding

The colors are the same! That's no help.

**Comment by stalkerg** [comment]
> If you've just typed a { character then your finger is already on the shift key!

Yes, I agree. 

> If that were true in this context, then we would write HTML like this:

it's obviously working if you have not so many keywords. In svelte we have only if, endif, each, endeach, await, endawait
Again you still can use / like {each}{/each} {if}{/if} yeah I know we will have shift but it's same as html tag.

**Comment by mindplay-dk** [comment]
I'd want a low-noise syntax that resembles JS as much as possible - I don't agree with the way you prioritize syntax concerns, so I just don't think this project is for me.

Thanks for the discussion.
